# pyproject.toml
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "human_cli"
version = "0.1.0"
authors = []
description = ""

[project.scripts]
start = "commands:start"
